### ISSUE TITLE
Problems with closing and releasing an artifact

### ISSUE THREAD

**Issue by pwittchen** [Codearte/gradle-nexus-staging-plugin#72]
Hi,

I tried to use your plugin to close and release my artifact from CLI, but it didn't work :-(.

I typed:

```
./gradlew closeAndReleaseRepository
```

and got something like this:

```
:closeRepository
Error parsing 'text/html' response
groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is '<' with an int value of 60
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
<html>
^
	at groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:206)
	at groovy.json.internal.JsonParserCharArray.decodeValue(JsonParserCharArray.java:157)
	at groovy.json.internal.JsonParserCharArray.decodeFromChars(JsonParserCharArray.java:46)
	at groovy.json.internal.JsonParserCharArray.parse(JsonParserCharArray.java:384)
	at groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:128)
	at groovy.json.JsonSlurper.parse(JsonSlurper.java:221)
	at groovyx.net.http.ParserRegistry.parseJSON(ParserRegistry.java:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1080)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at groovyx.net.http.HTTPBuilder.parseResponse(HTTPBuilder.java:560)
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:489)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1142)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1076)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
	at groovyx.net.http.RESTClient.get(RESTClient.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1080)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at io.codearte.gradle.nexus.infra.SimplifiedHttpJsonRestClient.prepareAndSendRequest(SimplifiedHttpJsonRestClient.groovy:63)
	at io.codearte.gradle.nexus.infra.SimplifiedHttpJsonRestClient.sendRequestHandlingErrors(SimplifiedHttpJsonRestClient.groovy:45)
	at io.codearte.gradle.nexus.infra.SimplifiedHttpJsonRestClient.get(SimplifiedHttpJsonRestClient.groovy:36)
	at io.codearte.gradle.nexus.logic.RepositoryFetcher.getRepositoryIdWithGivenStateForStagingProfileId(RepositoryFetcher.groovy:23)
	at io.codearte.gradle.nexus.logic.RepositoryFetcher.getOpenRepositoryIdForStagingProfileId(RepositoryFetcher.groovy:14)
	at io.codearte.gradle.nexus.CloseRepositoryTask$_findOneOpenRepositoryIdForStagingProfileIdWithRetrying_closure1.doCall(CloseRepositoryTask.groovy:40)
	at io.codearte.gradle.nexus.CloseRepositoryTask$_findOneOpenRepositoryIdForStagingProfileIdWithRetrying_closure1.doCall(CloseRepositoryTask.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at io.codearte.gradle.nexus.logic.OperationRetrier.doWithRetry(OperationRetrier.groovy:29)
	at io.codearte.gradle.nexus.CloseRepositoryTask.findOneOpenRepositoryIdForStagingProfileIdWithRetrying(CloseRepositoryTask.groovy:40)
	at io.codearte.gradle.nexus.CloseRepositoryTask.doAction(CloseRepositoryTask.groovy:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
GET request failed. 500: Server Error, body: <empty>
:closeRepository FAILED
1 actionable task: 1 executed
```

Here's my top-level `build.gradle` file:

https://github.com/pwittchen/ReactiveNetwork/blob/RxJava2.x/build.gradle

I'm looking forward to your help because I really want to do whole release via CLI.

Regards,
Piotr

**Comment by szpak** [comment]
Hi Piotrek. You've got `500: Server error`. Server didn't like something you sent or had some internal problems. You can call it with `--debug` to see the original HTML in the response (it's somehow common, there could be a better error message), however, looking at your configuration the problem may be related to:
> stagingProfileId = "reactivenetwork-rx2" //when not defined will be got from server using "packageGroup"

Which seems to be a verbatim copy of from the README. A few paragraphs later there is:

> stagingProfileId (optional) - the staging profile used to release given project - can be get with the getStagingProfile task - when not set one additional request is send to the Nexus server to determine the value using packageGroup

Therefore, to fix the problem you (probably) only need to call the `getStagingProfile` task to get the `stagingProfileId` (it's not your login - your account can have access to multiple staging profiles).

**Comment by pwittchen** [comment]
Thanks for quick reply. I've got staging profile id with this gradle task. It looks like a random string with letters and numbers. Is it safe to add it to the GitHub repo or I should hide it from the public like username and password? I also have another question: Is it possible to test my configuration without publishing artifact to the sonatype server? I recently published new release and I don't want to do it again just to test the plugin.

**Comment by szpak** [comment]
Regarding security the same came to my mind when I was writing that plugin. To use that ID your credentials are required (I hope that you use an [auth token](https://solidsoft.wordpress.com/2015/09/08/deploy-to-maven-central-using-api-key-aka-auth-token) instead of username and password). Having your credentials ID can be fetched. Personally, I don't treat it as a secret. It's just an ID (which as every ID could be used to do some tricky attack - however, IMHO it's very unlikely). Besides it is displayed in the build logs to make debugging easier.

Yes, definitely you can. To automatically test my [Continuous Delivery plugin](https://github.com/szpak/CDeliveryBoy/) (in acceptance tests) I use a toy project which instead of publishing to Maven Central it published to `/dev/null` as the Nexus side. However, much easier is just to call only the `closeRepository` tasks which closes the staging repository. Then, you can take a look at the artifacts prepared to release using the Nexus OSS web [UI](http://oss.sonatype.org/) and release it manually (or drop if needed and try again).

**Comment by pwittchen** [comment]
Great! Thanks, I'll check it later. :-)

**Comment by szpak** [comment]
Most likely `stagingProfileId` will fix the your problem. Nevertheless, feel free to reopen this issue otherwise.

**Comment by pwittchen** [comment]
Ok, I've checked it a second ago and it works! Thanks for help.

PS. It would be helpful to create `drop` gradle task. E.g. when someone would like to drop artifact without releasing.

**Comment by szpak** [comment]
Great.

There is a separate [issue](https://github.com/Codearte/gradle-nexus-staging-plugin/issues/17) for that. In fact, under the hood everything is implemented (I use it in my integration/acceptance tests). However, it can lead to some extra errors and confusion and I don't see a good use case for that. Dropping is quite rare operation in a production deployment and (if needed) can be done via the UI.
